<?php

declare(strict_types=1);

namespace Omega\Gettext;

use Closure;
use Omega\Gettext\Generator\ArrayGenerator;
use InvalidArgumentException;

use function get_debug_type;
use function sprintf;
use function array_pop;
use function array_replace_recursive;
use function count;
use function explode;
use function is_array;
use function is_bool;
use function is_int;
use function is_string;
use function preg_match;
use function rtrim;
use function str_repeat;
use function str_replace;
use function trim;

/**
 * Pure-PHP gettext translator working on dictionaries loaded from PHP arrays.
 *
 * Dictionaries follow the format produced by ArrayGenerator/JsonGenerator:
 * one file per domain returning `domain`, `plural-forms` and `messages`.
 * Plural formulas are compiled once per domain into closures; lookups fall
 * back to the source strings whenever the domain or the entry is missing,
 * so calls never fail because of an incomplete catalog.
 *
 * @phpstan-consistent-constructor
 */
class Translator implements TranslatorInterface
{
    /** @var string|null Default domain used when a lookup does not specify one. */
    protected ?string $domain = null;

    /** @var array<string, array<string, array<string, list<string>|string>>> Domain > context > original > texts. */
    protected array $dictionary = [];

    /** @var array<string, array{count: int, code: string, function?: Closure}> Compiled plural rules per domain. */
    protected array $plurals = [];

    /**
     * Builds a translator from in-memory catalogs.
     *
     * @param Translations ...$allTranslations One or more catalogs to import.
     *
     * @return static The configured translator instance.
     */
    public static function createFromTranslations(Translations ...$allTranslations): Translator
    {
        $translator = new static();
        $arrayGenerator = new ArrayGenerator();

        foreach ($allTranslations as $translations) {
            $translator->addTranslations(
                $arrayGenerator->generateArray($translations)
            );
        }

        return $translator;
    }

    /**
     * Loads new dictionaries from PHP files generated by ArrayGenerator.
     *
     * The first loaded domain becomes the default one.
     *
     * @param string ...$files Paths of PHP files returning a dictionary array.
     *
     * @return self This object, for method chaining.
     *
     * @throws InvalidArgumentException If a file does not return an array.
     */
    public function loadTranslations(string ...$files): self
    {
        foreach ($files as $file) {
            $translations = include $file;

            if (!is_array($translations)) {
                throw new InvalidArgumentException('Invalid translations file: it must return an array');
            }

            $this->addTranslations($translations);
        }

        return $this;
    }

    /**
     * Add new translations to the dictionary.
     *
     * @param array<array-key, mixed> $translations Dictionary holding `domain`,
     *        optional `plural-forms` and `messages` keys.
     *
     * @throws InvalidArgumentException If a compiled plural expression is not a closure.
     *
     * @return self This object, for method chaining.
     */
    public function addTranslations(array $translations): self
    {
        $domain = $translations['domain'] ?? '';

        if (!is_string($domain)) {
            $domain = '';
        }

        //Set the first domain loaded as default domain
        if ($this->domain === null) {
            $this->domain = $domain;
        }

        $messages = $translations['messages'] ?? [];

        if (!is_array($messages)) {
            $messages = [];
        }

        if (isset($this->dictionary[$domain])) {
            $merged = array_replace_recursive($this->dictionary[$domain], self::normalizeMessages($messages));

            $this->dictionary[$domain] = self::normalizeMessages($merged);

            return $this;
        }

        $pluralForms = $translations['plural-forms'] ?? null;

        if (is_string($pluralForms) && $pluralForms !== '') {
            $chunks = explode(';', $pluralForms, 2);
            $count = trim($chunks[0]);
            $code = trim($chunks[1] ?? '');

            // extract just the expression turn 'n' into a php variable '$n'.
            // Slap on a return keyword and semicolon at the end.
            $this->plurals[$domain] = [
                'count' => (int) str_replace('nplurals=', '', $count),
                'code' => 'return ' . self::fixTerseIfs(rtrim(str_replace('plural=', '', $code), ';')) . ';',
            ];
        }

        $this->dictionary[$domain] = self::normalizeMessages($messages);

        return $this;
    }

    /**
     * Keeps only the well-formed entries of a messages structure:
     * context => original => (string translation | list<string> plural translations).
     *
     * @param array<array-key, mixed> $messages
     * @return array<string, array<string, list<string>|string>>
     */
    /**
     * Keeps only well-formed entries: context > original > (string | list<string>).
     *
     * Malformed rows are silently dropped instead of poisoning the dictionary.
     *
     * @param array<array-key, mixed> $messages Raw structure coming from a dictionary file.
     *
     * @return array<string, array<string, list<string>|string>> Normalized messages.
     */
    private static function normalizeMessages(array $messages): array
    {
        $normalized = [];

        foreach ($messages as $contextKey => $contextTranslations) {
            if (!is_array($contextTranslations)) {
                continue;
            }

            $context = [];

            foreach ($contextTranslations as $originalKey => $value) {
                if (is_string($value)) {
                    $context[(string) $originalKey] = $value;
                    continue;
                }

                if (!is_array($value)) {
                    continue;
                }

                $plurals = [];

                foreach ($value as $pluralValue) {
                    if (is_string($pluralValue)) {
                        $plurals[] = $pluralValue;
                    }
                }

                if ($plurals !== []) {
                    $context[(string) $originalKey] = $plurals;
                }
            }

            if ($context !== []) {
                $normalized[(string) $contextKey] = $context;
            }
        }

        return $normalized;
    }

    /**
     * Overrides the default domain used by lookups without an explicit one.
     *
     * @param string $domain Name of an already loaded domain.
     *
     * @return self This object, for method chaining.
     */
    public function defaultDomain(string $domain): self
    {
        $this->domain = $domain;

        return $this;
    }

    /**
     * Marks a string for extraction without translating it.
     *
     * @param string $original Source string to mark as translatable..
     *
     * @return string The same original string, unchanged.
     */
    public function noop(string $original): string
    {
        return $original;
    }

    /**
     * Returns the translation of the original string.
     *
     * @param string $original Source string to translate..
     *
     * @return string The translated text, or the original when missing.
     */
    public function gettext(string $original): string
    {
        return $this->translate(null, null, $original);
    }

    /**
     * Returns the translation for the singular or plural form of a string.
     *
     * @param string $original Singular source string..
     * @param string $plural Plural source string..
     * @param int $value Number used to pick the plural form..
     *
     * @return string The translated text, or the closest source form when missing.
     */
    public function ngettext(string $original, string $plural, int $value): string
    {
        return $this->translatePlural(null, null, $original, $plural, $value);
    }

    /**
     * @param string $domain Domain to search in..
     * @param string $original Singular source string..
     * @param string $plural Plural source string..
     * @param int $value Number used to pick the plural form..
     *
     * @return string The translated text, or the closest source form when missing.
     */
    public function dngettext(string $domain, string $original, string $plural, int $value): string
    {
        return $this->translatePlural($domain, null, $original, $plural, $value);
    }

    /**
     * @param string $context Context to search in..
     * @param string $original Singular source string..
     * @param string $plural Plural source string..
     * @param int $value Number used to pick the plural form..
     *
     * @return string The translated text, or the closest source form when missing.
     */
    public function npgettext(string $context, string $original, string $plural, int $value): string
    {
        return $this->translatePlural(null, $context, $original, $plural, $value);
    }

    /**
     * Returns the translation of the original string within a context.
     *
     * @param string $context Context to search in..
     * @param string $original Source string to translate..
     *
     * @return string The translated text, or the original when missing.
     */
    public function pgettext(string $context, string $original): string
    {
        return $this->translate(null, $context, $original);
    }

    /**
     * Returns the translation of the original string within a domain.
     *
     * @param string $domain Domain to search in..
     * @param string $original Source string to translate..
     *
     * @return string The translated text, or the original when missing.
     */
    public function dgettext(string $domain, string $original): string
    {
        return $this->translate($domain, null, $original);
    }

    /**
     * Returns the translation of the original string within a domain and context.
     *
     * @param string $domain Domain to search in..
     * @param string $context Context to search in..
     * @param string $original Source string to translate..
     *
     * @return string The translated text, or the original when missing.
     */
    public function dpgettext(string $domain, string $context, string $original): string
    {
        return $this->translate($domain, $context, $original);
    }

    /**
     * Combines domain, context and plural resolution in a single lookup.
     *
     * @param string $domain Domain to search in..
     * @param string $context Context to search in..
     * @param string $original Singular source string..
     * @param string $plural Plural source string..
     * @param int $value Number used to pick the plural form..
     *
     * @return string The translated text, or the closest source form when missing.
     */
    public function dnpgettext(string $domain, string $context, string $original, string $plural, int $value): string
    {
        return $this->translatePlural($domain, $context, $original, $plural, $value);
    }

    /**
     * Performs a singular lookup, falling back to the original string.
     *
     * @param string|null $domain Domain to search in, or null for the default one.
     * @param string|null $context Context to search in, or null for the default one.
     * @param string $original Source string to translate.
     *
     * @return string The translated text, or the original when missing or empty.
     */
    protected function translate(?string $domain, ?string $context, string $original): string
    {
        $translation = $this->getTranslation($domain, $context, $original);

        if (isset($translation[0]) && $translation[0] !== '') {
            return $translation[0];
        }

        return $original;
    }

    /**
     * Performs a plural lookup using the compiled formula of the domain.
     *
     * Falls back to the original/plural strings when the entry is missing or
     * the picked index has no text.
     *
     * @param string|null $domain Domain to search in, or null for the default one.
     * @param string|null $context Context to search in, or null for the default one.
     * @param string $original Singular source string.
     * @param string $plural Plural source string.
     * @param int $value Number used to pick the plural form.
     *
     * @return string The translated text, or the closest source form when missing.
     */
    protected function translatePlural(
        ?string $domain,
        ?string $context,
        string $original,
        string $plural,
        int $value
    ): string {
        $translation = $this->getTranslation($domain, $context, $original);
        $key = $this->getPluralIndex($domain, $value, $translation === null);

        if (isset($translation[$key]) && $translation[$key] !== '') {
            return $translation[$key];
        }

        return ($key === 0) ? $original : $plural;
    }

    /**
     * Searches a translation in the dictionary and normalizes it to a list.
     *
     * Singular entries are wrapped into single-element lists so both shapes
     * can be indexed uniformly.
     *
     * @param string|null $domain Domain to search in, or null for the default one.
     * @param string|null $context Context to search in, or null for the default one.
     * @param string $original Source string to look up.
     *
     * @return list<string>|null The indexed texts, or null when not found.
     */
    protected function getTranslation(?string $domain, ?string $context, string $original): ?array
    {
        if ($domain === null) {
            $domain = $this->domain ?? '';
        }

        if ($context === null) {
            $context = '';
        }

        $value = $this->dictionary[$domain][$context][$original] ?? null;

        if ($value === null) {
            return null;
        }

        return is_array($value) ? $value : [$value];
    }

    /**
     * Evaluates the compiled plural formula of the domain for a number.
     *
     * When the domain is unknown, or the caller marks a fallback, a simple
     * `n == 1` rule is applied instead.
     *
     * @param string|null $domain Domain owning the formula, or null for the default one.
     * @param int $n Number used to evaluate the formula.
     * @param bool $fallback Force the simple rule regardless of the formula.
     *
     * @throws InvalidArgumentException If the compiled expression returns a non-integer.
     *
     * @return int Zero-based index of the plural form to use.
     */
    protected function getPluralIndex(?string $domain, int $n, bool $fallback): int
    {
        if ($domain === null) {
            $domain = $this->domain ?? '';
        }

        //Not loaded domain or translation, use a fallback
        if (!isset($this->plurals[$domain]) || $fallback) {
            return $n == 1 ? 0 : 1;
        }

        if (!isset($this->plurals[$domain]['function'])) {
            $function = eval("return function (\$n) { {$this->plurals[$domain]['code']} };");

            if (!$function instanceof Closure) {
                throw new InvalidArgumentException('Invalid plural form expression');
            }

            $this->plurals[$domain]['function'] = $function;
        }

        $result = ($this->plurals[$domain]['function'])($n);

        if (is_bool($result)) {
            return $result ? 1 : 0;
        }

        if (is_int($result)) {
            return $result;
        }

        throw new InvalidArgumentException(sprintf(
            'The plural form expression must return an integer index, %s returned',
            get_debug_type($result)
        ));
    }

    /**
     * Prepares a gettext plural expression to be evaluated by PHP.
     *
     * Nested ternary IFs are parenthesized (PHP would misinterpret them) and
     * the variable `n` is prefixed with `$`.
     *
     * Example:
     *
     * ```
     * $n==1 ? 0 : $n%10>=2 && $n%10<=4 ? 1 : 2
     * ```
     *
     * becomes:
     *
     * ```
     * $n==1 ? 0 : ($n%10>=2 && $n%10<=4 ? 1 : 2)
     * ```
     *
     * @param string $pluralForms Raw gettext expression.
     *
     * @throws InvalidArgumentException If it contains characters outside the allowed set.
     *
     * @return string PHP-evaluable expression.
     */
    private static function fixTerseIfs(string $pluralForms): string
    {
        if (preg_match('/[^<>|%&!?:=n()\d\s]/', $pluralForms)) {
            throw new InvalidArgumentException('Invalid plural form expression');
        }
        $pieces = explode(':', str_replace('n', '$n', $pluralForms));
        $last = array_pop($pieces);
        $pluralForms = '';
        foreach ($pieces as $piece) {
            $pluralForms .= "$piece:(";
        }
        return $pluralForms . $last . str_repeat(')', count($pieces));
    }
}
